services:
  db:
    image: postgres:15
    container_name: diaria-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: diaria
      POSTGRES_PASSWORD: diaria_password
      POSTGRES_DB: diaria_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Se você tiver scripts de inicialização (por exemplo em prisma/migrations),
      # pode montar um diretório aqui para rodar os scripts automaticamente
      # - ./prisma/initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U diaria -d diaria_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: diaria-pgadmin
    restart: unless-stopped
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:

networks:
  default:
    name: diaria-network

